function Result = bench_harness_selfcheck()
    % bench_harness_selfcheck  Prove the benchmark harness works end to end.
    %
    % Deliberately uses nothing but core MATLAB: no AstroPack functions, no
    % data files, no toolboxes. If this case goes red, the problem is the
    % harness or the environment, not the science.
    %
    % Keep it. When a real case regresses, this one tells you at a glance
    % whether to suspect the pipeline or the plumbing.
    %
    % It also demonstrates all three tolerance directions.

    rng(1234, 'twister');   % local seed: independent of the caller's

    % A fixed, reproducible computation with a known closed form.
    N       = 10000;
    Samples = randn(N, 1);
    Grid    = linspace(0, pi, N).';
    Integral = trapz(Grid, sin(Grid));      % analytic value: exactly 2

    Result.metrics = struct( ...
        'sampleMean',        mean(Samples), ...
        'sampleStd',         std(Samples), ...
        'trapzSinAbsError',  abs(Integral - 2), ...
        'elementsProcessed', N);

    Result.tolerances = struct( ...
        ... % Sampling noise around 0; stable only because the seed is fixed.
        'sampleMean',       struct('abs', 1e-12, 'rel', 0, ...
                                   'direction', 'any'), ...
        'sampleStd',        struct('abs', 1e-12, 'rel', 0, ...
                                   'direction', 'any'), ...
        ... % Quadrature error: smaller is strictly better.
        'trapzSinAbsError', struct('abs', 1e-9, 'rel', 0.1, ...
                                   'direction', 'lower_is_better'), ...
        ... % Work done: must not silently shrink.
        'elementsProcessed', struct('abs', 0, 'rel', 0, ...
                                    'direction', 'higher_is_better'));

    Result.meta = struct( ...
        'description', ['Harness self-check: core-MATLAB determinism and ' ...
                        'tolerance handling. No AstroPack dependency.'], ...
        'dataset',     'None -- generated in-process from a fixed seed.', ...
        'owner',       'CI maintainer');
end
